"""MoWA model modules."""

from .action_bridge import (
    MoWAActionBridge,
    MoWAActionBridgeConfig,
    MoWAActionBridgeOutput,
)
from .action_head_adapter import (
    MOWA_ACTION_HEAD_BINDINGS,
    MoWAActionHeadBinding,
    append_layerwise_bridge_tokens,
    append_single_sequence_bridge_tokens,
    append_vla_adapter_bridge_tokens,
    describe_mowa_action_head_bindings,
    fuse_mlp_bridge_features,
    resolve_mowa_action_head_binding,
)
from .future_latent_prior import (
    MoWAFutureLatentPrior,
    MoWAFutureLatentPriorConfig,
    MoWAFutureLatentPriorOutput,
    # Backward-compatible P1 aliases (deprecated)
    MoWAP1B0FutureLatentPrior,
    MoWAP1B0FutureLatentPriorConfig,
    MoWAP1B0FutureLatentPriorOutput,
)
from .hlcgci import (
    MoWAHLCGCI,
    MoWAHLCGCIConfig,
    MoWAHLCGCIOutput,
)
from .p0_heads import (
    MoWAFutureConstructibleHeads,
    MoWAFutureConstructibleHeadsConfig,
    MoWAFutureFeatureHeads,
    MoWAFutureFeatureHeadsConfig,
    MoWAFutureFeatures,
    MoWAFutureFullHeads,
    MoWAFutureFullHeadsConfig,
    build_mowa_future_constructible_batch_from_smoke,
    build_mowa_p0_constructible_batch_from_smoke,
    mowa_manual_sgd_step,
    # Backward-compatible P0 aliases (deprecated)
    MoWAP0ConstructibleHeads,
    MoWAP0ConstructibleHeadsConfig,
    MoWAP0FullHeads,
    MoWAP0FullHeadsConfig,
    P0FutureFeatures,
)
from starVLA.mowa_constants import (
    MOWA_FUTURE_CONSTRUCTIBLE_HEADS,
    MOWA_FUTURE_FEATURE_HEADS_SOURCE,
    MOWA_FUTURE_FEATURE_SOURCE_ALIASES,
    MOWA_FUTURE_FULL_HEADS,
    MOWA_FUTURE_HEAD_OUTPUT_DIMS,
    MOWA_FUTURE_MASKED_HEADS,
    MOWA_P0_CONSTRUCTIBLE_HEADS,
    MOWA_P0_FULLHEADS_FEATURE_SOURCE,
    MOWA_P0_FULL_HEADS,
    MOWA_P0_HEAD_OUTPUT_DIMS,
    MOWA_P0_MASKED_HEADS,
    MOWA_STARFLOW_CONDITION_PROBE_FEATURE_SOURCE,
)

__all__ = [
    "MOWA_ACTION_HEAD_BINDINGS",
    "MOWA_FUTURE_CONSTRUCTIBLE_HEADS",
    "MOWA_FUTURE_FEATURE_HEADS_SOURCE",
    "MOWA_FUTURE_FEATURE_SOURCE_ALIASES",
    "MOWA_FUTURE_FULL_HEADS",
    "MOWA_FUTURE_HEAD_OUTPUT_DIMS",
    "MOWA_FUTURE_MASKED_HEADS",
    "MOWA_P0_CONSTRUCTIBLE_HEADS",
    "MOWA_P0_FULLHEADS_FEATURE_SOURCE",
    "MOWA_P0_FULL_HEADS",
    "MOWA_P0_HEAD_OUTPUT_DIMS",
    "MOWA_P0_MASKED_HEADS",
    "MOWA_STARFLOW_CONDITION_PROBE_FEATURE_SOURCE",
    "MoWAActionBridge",
    "MoWAActionBridgeConfig",
    "MoWAActionBridgeOutput",
    "MoWAActionHeadBinding",
    "MoWAFutureLatentPrior",
    "MoWAFutureLatentPriorConfig",
    "MoWAFutureLatentPriorOutput",
    "MoWAHLCGCI",
    "MoWAHLCGCIConfig",
    "MoWAHLCGCIOutput",
    "MoWAFutureConstructibleHeads",
    "MoWAFutureConstructibleHeadsConfig",
    "MoWAFutureFeatureHeads",
    "MoWAFutureFeatureHeadsConfig",
    "MoWAFutureFeatures",
    "MoWAFutureFullHeads",
    "MoWAFutureFullHeadsConfig",
    "MoWAP0ConstructibleHeads",
    "MoWAP0ConstructibleHeadsConfig",
    "MoWAP0FullHeads",
    "MoWAP0FullHeadsConfig",
    "P0FutureFeatures",
    "MoWAP1B0FutureLatentPrior",
    "MoWAP1B0FutureLatentPriorConfig",
    "MoWAP1B0FutureLatentPriorOutput",
    "build_mowa_future_constructible_batch_from_smoke",
    "build_mowa_p0_constructible_batch_from_smoke",
    "append_layerwise_bridge_tokens",
    "append_single_sequence_bridge_tokens",
    "append_vla_adapter_bridge_tokens",
    "describe_mowa_action_head_bindings",
    "fuse_mlp_bridge_features",
    "mowa_manual_sgd_step",
    "resolve_mowa_action_head_binding",
]
